title: Cosmin Lupu
bio: Network Engineer
description: Shower Thought
external-image: false
#picture: assets/images/profile.webp
picture: assets/images/1590875937009.jpg
# your site color theme, true for dark theme,
# false to light theme, auto to switch with system.
dark-theme: auto
resume: false
resume-external: false
resume-url: "https://google.com/?q=my+resume"
url: "https://panzerfly.github.io"
knowledge-url: "https://panzerfly.gitbook.io/knowledge/"
permalink: "/:title/"
#disqus:
#  shortname: cosminl
#  categories:
#    - blog
#    - project
# youtube: madecanggih
# instagram: madecanggih
# twitter: madecanggih
#github: madeindra
email: cosmin@pm.me
linkedin: cosmin
# adplist: made-indra
#authors:
#  madeindra:
#    name: Cosmin LUPU
#    bio: Network Engineer
#    external-image: false
    #picture: assets/images/profile.webp
#    picture: assets/images/1590875937009.jpg
    # twitter: mdeindra
width: normal
pagination:
  enabled: false
  sort_reverse: true
  title: ":title"
  per_page: 5
  permalink: "/:num/"
projects: false
about: false
blog: false
knowledge: false
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
defaults:
  - scope:
      path: ""
      layout: post
    values:
      hidden: false
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
jekyll-mentions:
  base_url: "https://github.com"
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - node_modules
  - vendor
